### ISSUE TITLE
Parameter Store always defaults to SecureString

### ISSUE THREAD

**Issue by Kazzer** [unbounce/iidy#121]
Many of the strings set in parameter store do not need to be secure strings, and ones that are often are echoed by default.

I think a couple changes might be nice:
* String is the default type
* Strings are echoed
* a flag exists (eg. `--encrypt`) to upload as SecureString
* SecureStrings are not echoed

**Comment by tavisrudd** [comment]
By `Strings are echoed` do you mean that we should echo the input after `iidy param set`?

**Comment by tavisrudd** [comment]
@jpb @pauloancheta what do you think about this?

**Comment by pauloancheta** [comment]
+1 for uploading a non-secure string.
+1 on strings are echoed. It would be nice to have feedback once the parameter has been set. While we shouldn't echo secure strings, we should have a feedback to let the user know that it has been uploaded.

I do like the flag of `--encrypt` but I'm not so sure about the defaults. I am leaning towards to defaulting to encrypted because people should be more aware that they are uploading a non-secure string.

Having it very easy to upload a non secure string might be a problem for auditing.

**Comment by jpb** [comment]
It seems to me that the main use-case of using parameter store here is to store things that are secret - if they were not secret then the codebase seems like a better place for them. I feel like this change may be a foot-gun and I fear that changing the behaviour would result secrets being store as plain text in parameter store.

I agree that both echoing secrets and inadvertently storing a secret unencrypted in parameter store are both security concerns, but I feel in this use-case the latter would be a larger problem.

We already have `iidy param get --no-decrypt` which effectively is a no-echo for SecureString types, and `iidy param put --type ...` to use String or StringList instead of the default SecureString.

**Comment by tavisrudd** [comment]
I prefer keeping `--type SecureString` as the default, especially as AWS have indicated that they're adding support for SecureStrings as an CFN parameter type in the near future. 

Which context are we talking about echoing strings? `iidy param set` doesn't echo anything. `iidy param get` and related commands decrypt by default.
